-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2023-11-02 07:40:06 SGT
--   site:      DB2/UDB 7.1
--   type:      DB2/UDB 7.1



CREATE TABLE admin 
    (
     id_admin INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, 
     username VARCHAR (20) NOT NULL , 
     password VARCHAR (20) NOT NULL , 
     admin_id_admin INTEGER 
    )
;

CREATE TABLE diamond 
    (
     id_item INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, 
     jumlah INTEGER NOT NULL 
    )
;

CREATE TABLE item 
    (
     id_item INTEGER NOT NULL PRIMARY KEY  AUTO_INCREMENT, 
     harga_item INTEGER NOT NULL , 
     admin_id_admin INTEGER NOT NULL , 
     transaksi_id_transaksi INTEGER , 
     stok INTEGER NOT NULL 
    )
;

CREATE TABLE transaksi 
    (
     id_transaksi INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, 
     total_pembayaran INTEGER NOT NULL , 
     waktu_konfirmasi TIMESTAMP NOT NULL , 
     user_id_user INTEGER NOT NULL 
    )
;
CREATE UNIQUE INDEX transaksi__IDX
    ON transaksi 
    (user_id_user);

CREATE TABLE twilight_pass 
    (
     level INTEGER NOT NULL , 
     id_item INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT 
    )
;

CREATE TABLE "user" 
    (
     id_user INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, 
     username VARCHAR (20) NOT NULL , 
     password VARCHAR (20) NOT NULL , 
     jumlah_saldo INTEGER NOT NULL , 
     transaksi_id_transaksi INTEGER NOT NULL 
    )
;
CREATE UNIQUE INDEX user__IDX
    ON "user" 
    (transaksi_id_transaksi);

CREATE TABLE weekly_pass 
    (
     durasi TIMESTAMP NOT NULL , 
     id_item INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT
    )
;

ALTER TABLE admin
    ADD CONSTRAINT admin_admin_FK FOREIGN KEY
    ( 
     admin_id_admin
    ) 
    REFERENCES admin 
    ( 
     id_admin
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
;

ALTER TABLE diamond
    ADD CONSTRAINT diamond_item_FK FOREIGN KEY
    ( 
     id_item
    ) 
    REFERENCES item 
    ( 
     id_item
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
;

ALTER TABLE item
    ADD CONSTRAINT item_admin_FK FOREIGN KEY
    ( 
     admin_id_admin
    ) 
    REFERENCES admin 
    ( 
     id_admin
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
;

ALTER TABLE item
    ADD CONSTRAINT item_transaksi_FK FOREIGN KEY
    ( 
     transaksi_id_transaksi
    ) 
    REFERENCES transaksi 
    ( 
     id_transaksi
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
;

ALTER TABLE transaksi
    ADD CONSTRAINT transaksi_user_FK FOREIGN KEY
    ( 
      user_id_user
    ) 
    REFERENCES "user" 
    ( 
     id_user
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
;

ALTER TABLE twilight_pass
    ADD CONSTRAINT twilight_pass_item_FK FOREIGN KEY
    ( 
     id_item
    ) 
    REFERENCES item 
    ( 
     id_item
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
;

ALTER TABLE "user"
    ADD CONSTRAINT user_transaksi_FK FOREIGN KEY
    ( 
     transaksi_id_transaksi
    ) 
    REFERENCES transaksi 
    ( 
     id_transaksi
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
;

ALTER TABLE weekly_pass
    ADD CONSTRAINT weekly_pass_item_FK FOREIGN KEY
    ( 
     id_item
    ) 
    REFERENCES item 
    ( 
     id_item
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             2
-- ALTER TABLE                             15
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE STRUCTURED TYPE                   0
-- CREATE ALIAS                             0
-- CREATE BUFFERPOOL                        0
-- CREATE DATABASE                          0
-- CREATE DISTINCT TYPE                     0
-- CREATE INSTANCE                          0
-- CREATE NODE GROUP                        0
-- CREATE TABLESPACE                        0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
